package com.brap.common.response;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public enum ErrorCode {
    A401_TOKEN_EXPIRED("A401"),
    A401_NOT_AUTHORIZED("PERMISSION_DENIED"),
    A403_NOT_AUTHORIZED("PERMISSION_DENIED"),
    A401_TOKEN_PROCESSING_FAILURE("A401"),
    A400_INVALID_ROLE("A400"),
    A400_INVALID_AUTH_STRING("A400"),
    A400_INVALID_API_KEY("A400"),
    A400_APPOINTMENT_BAD_REQUEST("A400"),
    A400_INVALID_GUID("INVALID_GUID"),
    A400_APPOINTMENT_NOT_COMPLETE("APPOINTMENT_NOT_COMPLETE"),
    A201_APPOINTMENT_CREATED_COULD_NOT_DETERMINE_ID("A201"),
    AR404_APPOINTMENT_RATING_NOT_FOUND("APPOINTMENT_RATING_NOT_FOUND"),
    AR409_APPOINTMENT_RATING_ALREADY_EXISTS("APPOINTMENT_RATING_ALREADY_EXISTS"),
    AGR_404_AGREEMENT_DOES_NOT_EXIST("AGREEMENT_DOES_NOT_EXIST"),
    AGR_409_AGREEMENT_ALREADY_EXISTS("AGREEMENT ALREADY EXISTS"),
    C400_CLINIC_BAD_REQUEST("C400"),
    C401_CLINIC_UNAUTHORIZED("C401"),
    C503_CLINIC_UPSTREAM_FAILURE("C503"),
    CA409_CLINIC_AGREEMENT_ALREADY_EXISTS("CLINIC_AGREEMENT_ALREADY_EXISTS"),
    CA404_CLINIC_AGREEMENT_DOES_NOT_EXIST("ClINIC_AGREEMENT_DOES_NOT_EXIST"),
    CM404_CLINIC_MAPPING_DOES_NOT_EXIST("CLINIC_MAPPING_DOES_NOT_EXIST"),
    CM400_CLINIC_MAPPING_VIEW_INVALID_REQUEST("CLINIC_MAPPING_VIEW_INVALID_REQUEST"),
    PR404_MEMBER_PRICE_NOT_FOUND("MEMBER_PRICE_NOT_FOUND"),
    CACHE_500_CACHE_DATA_LOADING("COULD_NOT_LOAD_DATA_FROM_CACHE"),
    CLIENT_408_DISCONNECT("CLIENT_DISCONNECT"),
    UPSTREAM_504_SOAP_TIMEOUT("UPSTREAM_SOAP_TIMEOUT"),
    UNEXPECTED_EXCEPTION("UnexpectedException"),
    UNKNOWN("UnknownErrorCode"),
	I403_IMAGE_SHOULD_NOT_BE_EMPTY("I403"),
    I500_UNABLE_TO_PERSIST_IMAGE("I500"),
	INVALID_REQUEST("INVALID_REQUEST"),
	USER_NOT_FOUND("USER_DOES_NOT_EXIST"),
	IMAGE_DOES_NOT_EXIST("IMAGE_DOES_NOT_EXIST"),
	I404_INTAKE_DOES_NOT_EXIST("I404"),
	W404_WELLNESS_AGREEMENT_DOES_NOT_EXIST("W404"),
	C404_CONSENT_DOES_NOT_EXIST("CONSENT_DOES_NOT_EXIST"),
	C409_CONSENT_ALREADY_EXISTS("CONSENT_ALREADY_EXISTS"),
	A404_APPOINTMENT_DOES_NOT_EXIST("APPOINTMENT_DOES_NOT_EXIST"),
	A404_INVALID_APPOINTMENT_RATING("INVALID_APPOINTMENT_RATING"),
	W404_WELLNESS_PLAN_DOES_NOT_EXIST("WELLNESS_PLAN_DOES_NOT_EXIST"),
    E400_INCORRECT_EMPLOYEE_ROLE("INCORRECT_EMPLOYEE_ROLE"),
    E400_UNKNOWN_EMPLOYEE_ROLE("UNKNOWN_EMPLOYEE_ROLE"),
    E400_EMPLOYEE_NOT_LINKED_CORRECTLY("EMPLOYEE_NOT_LINKED_CORRECTLY"),
    E404_EMPLOYEE_DOES_NOT_EXIST("EMPLOYEE_DOES_NOT_EXIST"),
    E404_EMPLOYEE_SURVEY_DATA_DOES_NOT_EXIST("EMPLOYEE_SURVEY_DATA_DOES_NOT_EXIST"),
    E410_EMPLOYEE_IS_INACTIVE("EMPLOYEE_IS_INACTIVE"),
    D404_DATA_DOES_NOT_EXIST("RECORD_DOES_NOT_EXIST"),
    EM_401_EMAIL_VERIFICATION_HAS_NOT_BEEN_VERIFIED("EMAIL_VERIFICATION_HAS_NOT_BEEN_VERIFIED"),
    EM_409_EMAIL_HAS_ALREADY_BEEN_VERIFIED("EMAIL_HAS_ALREADY_BEEN_VERIFIED"),
    EM_410_EMAIL_VERIFICATION_HAS_EXPIRED("EMAIL_VERIFICATION_HAS_EXPIRED"),
    EM_202_EMAIL_VERIFICATION_HAS_EXPIRED_AND_BEEN_RESENT("EMAIL_VERIFICATION_HAS_EXPIRED_AND_BEEN_RESENT"),
    EM_409_EMAIL_VERIFICATION_HAS_NOT_EXPIRED("EMAIL_VERIFICATION_HAS_NOT_EXPIRED"),
    EM_410_EMAIL_VERIFICATION_CONFLICT("EMAIL_VERIFICATION_CONFLICT"),
    EM_404_EMAIL_VERIFICATION_NOT_FOUND("EMAIL_VERIFICATION_COULD_NOT_BE_FOUND"),
    EM_409_EMAIL_VERIFICATION_ALREADY_EXISTS("EMAIL_VERIFICATION_ALREADY_EXISTS"),
    EM_500_CUATRO_EMAIL_IO_ERROR("ERROR_CREATING_CUATRO_EMAIL"),
    F_500_CUATRO_FILE_IO_ERROR("ERROR_HANDLING_CUATRO_FILE"),
    CU400_CUSTOMER_HAS_NON_UNIQUE_GLOBAL_IDS("CUSTOMER_HAS_NON_UNIQUE_GLOBAL_IDS"),
    CU404_CUSTOMER_GLOBAL_ID_DOES_NOT_EXIST("CUSTOMER_GLOBAL_ID_DOES_NOT_EXIST"),
    CU404_CUSTOMER_DOES_NOT_EXIST_IN_COEXIST("CUSTOMER_DOES_NOT_EXIST_IN_COEXIST"),
    CU500_CUSTOMER_CREATION_FAILED("CUSTOMER_CREATION_FAILED"),
    CU409_CUSTOMER_HAS_DUPLICATE_RECORDS("CUSTOMER_HAS_DUPLICATE_RECORDS"),
    CU400_INVALID_CREDIT_CARD("INVALID_CREDIT_CARD"),
    CU409_USERNAME_ALREADY_EXISTS("USERNAME_ALREADY_EXISTS"),
    CU410_CUSTOMER_NO_LONGER_ACTIVE("CUSTOMER_NO_LONGER_ACTIVE"),
    CU400_CUSTOMER_DOES_NOT_HAVE_AN_EMAIL_ADDRESS("CUSTOMER_DOES_NOT_HAVE_AN_EMAIL_ADDRESS"),
    CU409_MATCHING_CUSTOMER_RECORDS_FOUND_DURING_SIGNUP("MATCHING_CUSTOMER_RECORDS_FOUND_DURING_SIGNUP"),
    CUST_AGR_404_CUSTOMER_AGREEMENT_DOES_NOT_EXIST("CUSTOMER_AGREEMENT_DOES_NOT_EXIST"),
    CUST_AGR_409_CUSTOMER_AGREEMENT_ALREADY_EXISTS("CUSTOMER_AGREEMENT_ALREADY_EXISTS"),
    CUM400_CUSTOMER_MAPPING_NOT_UNIQUE("CUSTOMER_MAPPING_IS_NOT_UNIQUE"),
    CUM404_CUSTOMER_MAPPING_DOES_NOT_EXIST("CUSTOMER_MAPPING_DOES_NOT_EXIST"),
    FC409_FACIAL_CONSENT_ALREADY_EXISTS("FACIAL_CONSENT_ALREADY_EXISTS"),
    FC404_FACIAL_CONSENT_DOES_NOT_EXIST("FACIAL_CONSENT_DOES_NOT_EXIST"),
    D_400_INVALID_USER_REQUEST("REQUEST_IS_INVALID"),
    ET_404_EMAIL_TEMPLATE_NOT_FOUND("EMAIL_TEMPLATE_NOT_FOUND"),
    BAD_CUSTOMER_CREDENTIALS("BAD_CUSTOMER_CREDENTIALS"),
    BAD_EMPLOYEE_CREDENTIALS("BAD_EMPLOYEE_CREDENTIALS"),
    B404_BAD_DATA("BAD DATA"),
	U401_USER_UNAUTHORIZED("USER_UNAUTHORIZED"),
	I404_SKINCAREPRODUCTS_DOES_NOT_EXIST("SKINCAREPRODUCTS_DOES_NOT_EXIST"),
	I409_SKINCARE_CONSENT_ALREADY_EXIST("SKINCARE_CONSENT_ALREADY_EXIST"),
	I400_RESTRICTION_NOT_FOUND("RESTRICTION_NOT_FOUND"),
	SC404_WELLNESS_PLAN_NOT_FOUND("SKINCARE_WELLNESS_PLAN_NOT_FOUND"),
    SO404_SERVICE_OFFERING_NOT_FOUND("SERVICE_OFFERING_NOT_FOUND"),
	I404_SKINCARECONSENT_NOT_FOUND("I400_SKINCARECONSENT_NOT_FOUND"),
    PDF_500_UNABLE_TO_RENDER_PDF("PDF_500_UNABLE_TO_RENDER_PDF"),
    TEMPLATE_HTML_500_UNABLE_TO_RENDER_HTML("TEMPLATE_HTML_500_UNABLE_TO_RENDER_HTML"),
    TEMPLATE_400_FILE_IS_EMPTY("TEMPLATE_400_FILE_IS_EMPTY"),
    TEMPLATE_409_ALREADY_EXISTS("TEMPLATE_409_ALREADY_EXISTS"),
    TEMPLATE_404_DOES_NOT_EXIST("TEMPLATE_404_DOES_NOT_EXIST"),
    TEMPLATE_500_UNABLE_TO_PERSIST_TEMPLATE_FILE("TEMPLATE_500_UNABLE_TO_PERSIST_TEMPLATE_FILE"),
    TEMPLATE_500_UNABLE_TO_PARSE_TEMPLATE_FILE("TEMPLATE_500_UNABLE_TO_PERSIST_TEMPLATE_FILE"),
    CONTENT_404_CONTENT_NOT_FOUND("CONTENT_404_CONTENT_NOT_FOUND"),
    CONTENT_SET_404_CONTENT_SET_NOT_FOUND("CONTENT_SET_404_CONTENT_SET_NOT_FOUND"),
    CONTENT_409_CONTENT_ALREADY_EXISTS("CONTENT_409_CONTENT_ALREADY_EXISTS"),
	MEEVO_401_UNABLE_TO_LOGIN("MEEVO_401_UNABLE_TO_LOGIN"),
	DEFAULT_MERCHANT_ACCOUNT_NOT_FOUND("DEFAULT_MERCHANT_ACCOUNT_NOT_FOUND"),
	W404_PAYMENT_INFO_DOES_NOT_EXIST("W404_PAYMENT_INFO_DOES_NOT_EXIST"),
	CC404_CREDITCARD_TOKEN_NOT_FOUND("CC404_CREDITCARD_TOKEN_NOT_FOUND"),
	CC400_TRANSACTION_SETUP_ID_NOT_SPECIFIED("CC400_TRANSACTION_SETUP_ID_NOT_SPECIFIED"),
	CC400_TRANSACTION_SETUP_BAD_REQUEST("CC400_TRANSACTION_SETUP_BAD_REQUEST"),
    MIG500_MIGRATION_DEPENDENCY_UNAVAILABLE("MIG500_MIGRATION_DEPENDENCY_UNAVAILABLE"),
	AF400_APP_FEATURE_BAD_REQUEST("C400"),
	WA404_WELLNESS_AGREEMENT_NOT_FOUND("WA404_WA_NOT_FOUND"),
	WA404_WELLNESS_AGREEMENT_PDF_NOT_FOUND("WA404_PDF_NOT_FOUND");

    private static Map<String, ErrorCode> MAPPER = Collections.unmodifiableMap(initializeMapper());

    private final String code;

    ErrorCode(String code) {
        this.code = code;
    }

    public String getCode() {
        return this.code;
    }

    public static ErrorCode parseCode(String errorCodeString) {
        String normalizedErrorCodeString = errorCodeString.toUpperCase();
        ErrorCode errorCode = MAPPER.get(normalizedErrorCodeString);
        return errorCode != null ? errorCode : UNKNOWN;
    }

    private static Map<String, ErrorCode> initializeMapper() {
        Map<String, ErrorCode> mapper = new HashMap<>();
        for (ErrorCode errorCode : values()) {
            mapper.put(errorCode.code, errorCode);
        }
        return mapper;
    }

}
